version: '3'

services:
  grizzly:
    image: caddy:2.6.2
    container_name: grizzly
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/caddy/config.json:/tpdata/caddy/config.json"
      - "/tpdata/cert/:/tpdata/cert/certificates/acme-v02.api.letsencrypt.org-directory/${domain}/"
      - "/tpdata/web/:/tpdata/web/"
      - "/tpdata/caddy/logs/:/tpdata/caddy/logs/"
    command: caddy run --config /tpdata/caddy/config.json

  grizzly-mariadb:
    image: mariadb:10.7.3
    container_name: grizzly-mariadb
    restart: always
    network_mode: host
    environment:
      MYSQL_DATABASE: grizzly_db
      MYSQL_ROOT_PASSWORD: "${mariadb_pas}"
      TZ: Asia/Shanghai
    command: --port=9507

  grizzly-redis:
    image: redis:6.2.7
    container_name: grizzly-redis
    restart: always
    network_mode: host
    command: redis-server --requirepass ${redis_pass} --port 6378

  grizzly:
    image: jonssonyan/grizzly
    container_name: grizzly
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/web/:/tpdata/grizzly/webfile/"
      - "/tpdata/grizzly/logs/:/tpdata/grizzly/logs/"
      - "/tpdata/grizzly/config/:/tpdata/grizzly/config/"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=127.0.0.1"
      - "mariadb_port=9507"
      - "mariadb_user=root"
      - "mariadb_pas=${mariadb_pas}"
      - "redis_host=127.0.0.1"
      - "redis_port=6378"
      - "redis_pass=${redis_pass}"
      - "server_port=8081"

  grizzly-ui:
    image: jonssonyan/grizzly-ui
    container_name: grizzly-ui
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/grizzly-ui/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/tpdata/cert/:/tpdata/cert/"

  grizzly-core:
    image: jonssonyan/grizzly-core
    container_name: grizzly-core
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/grizzly-core/bin/xray/config/:/tpdata/grizzly-core/bin/xray/config/"
      - "/tpdata/grizzly-core/bin/trojango/config/:/tpdata/grizzly-core/bin/trojango/config/"
      - "/tpdata/grizzly-core/bin/hysteria/config/:/tpdata/grizzly-core/bin/hysteria/config/"
      - "/tpdata/grizzly-core/bin/naiveproxy/config/:/tpdata/grizzly-core/bin/naiveproxy/config/"
      - "/tpdata/grizzly-core/bin/hysteria2/config/:/tpdata/grizzly-core/bin/hysteria2/config/"
      - "/tpdata/grizzly-core/logs/:/tpdata/grizzly-core/logs/"
      - "/tpdata/grizzly-core/config/:/tpdata/grizzly-core/config/"
      - "/tpdata/cert/:/tpdata/cert/"
      - "/tpdata/web/:/tpdata/web/"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=127.0.0.1"
      - "mariadb_port=9507"
      - "mariadb_user=root"
      - "mariadb_pas=${mariadb_pas}"
      - "database=grizzly_db"
      - "account-table=account"
      - "redis_host=127.0.0.1"
      - "redis_port=6378"
      - "redis_pass=${redis_pass}"
      - "crt_path=/tpdata/cert/${domain}.crt"
      - "key_path=/tpdata/cert/${domain}.key"
      - "grpc_port=8100"
      - "server_port=8082"
